//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakingApp.L3.Cient.Wpf.OddoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OddoServiceReference.IServiceConsultation")]
    public interface IServiceConsultation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceConsultation/ConsulterSolde", ReplyAction="http://tempuri.org/IServiceConsultation/ConsulterSoldeResponse")]
        decimal ConsulterSolde(string value);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceConsultation/ConsulterSolde", ReplyAction="http://tempuri.org/IServiceConsultation/ConsulterSoldeResponse")]
        System.IAsyncResult BeginConsulterSolde(string value, System.AsyncCallback callback, object asyncState);
        
        decimal EndConsulterSolde(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceConsultationChannel : BakingApp.L3.Cient.Wpf.OddoServiceReference.IServiceConsultation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsulterSoldeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ConsulterSoldeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public decimal Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceConsultationClient : System.ServiceModel.ClientBase<BakingApp.L3.Cient.Wpf.OddoServiceReference.IServiceConsultation>, BakingApp.L3.Cient.Wpf.OddoServiceReference.IServiceConsultation {
        
        private BeginOperationDelegate onBeginConsulterSoldeDelegate;
        
        private EndOperationDelegate onEndConsulterSoldeDelegate;
        
        private System.Threading.SendOrPostCallback onConsulterSoldeCompletedDelegate;
        
        public ServiceConsultationClient() {
        }
        
        public ServiceConsultationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceConsultationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceConsultationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceConsultationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ConsulterSoldeCompletedEventArgs> ConsulterSoldeCompleted;
        
        public decimal ConsulterSolde(string value) {
            return base.Channel.ConsulterSolde(value);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginConsulterSolde(string value, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginConsulterSolde(value, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public decimal EndConsulterSolde(System.IAsyncResult result) {
            return base.Channel.EndConsulterSolde(result);
        }
        
        private System.IAsyncResult OnBeginConsulterSolde(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string value = ((string)(inValues[0]));
            return this.BeginConsulterSolde(value, callback, asyncState);
        }
        
        private object[] OnEndConsulterSolde(System.IAsyncResult result) {
            decimal retVal = this.EndConsulterSolde(result);
            return new object[] {
                    retVal};
        }
        
        private void OnConsulterSoldeCompleted(object state) {
            if ((this.ConsulterSoldeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ConsulterSoldeCompleted(this, new ConsulterSoldeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ConsulterSoldeAsync(string value) {
            this.ConsulterSoldeAsync(value, null);
        }
        
        public void ConsulterSoldeAsync(string value, object userState) {
            if ((this.onBeginConsulterSoldeDelegate == null)) {
                this.onBeginConsulterSoldeDelegate = new BeginOperationDelegate(this.OnBeginConsulterSolde);
            }
            if ((this.onEndConsulterSoldeDelegate == null)) {
                this.onEndConsulterSoldeDelegate = new EndOperationDelegate(this.OnEndConsulterSolde);
            }
            if ((this.onConsulterSoldeCompletedDelegate == null)) {
                this.onConsulterSoldeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnConsulterSoldeCompleted);
            }
            base.InvokeAsync(this.onBeginConsulterSoldeDelegate, new object[] {
                        value}, this.onEndConsulterSoldeDelegate, this.onConsulterSoldeCompletedDelegate, userState);
        }
    }
}
